#### Hospital Patient Data Analysis

In [39]:
import pandas as pd
import numpy as np
import warnings
warnings.filterwarnings('ignore')

1.Load the patient dataset and show summary with info().

In [40]:
### Load both data set
patients = pd.read_csv("Patient_Data.csv")
billing = pd.read_csv("Billing_Data.csv")
print("Patient Dataset Summary:")
print(patients.info())

Patient Dataset Summary:
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6 entries, 0 to 5
Data columns (total 7 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   PatientID       6 non-null      int64
 1   Name            6 non-null      object
 2   Department      6 non-null      object
 3   Doctor          6 non-null      object
 4   BillAmount      4 non-null      float64
 5   ReceptionistID  6 non-null      int64
 6   CheckInTime     6 non-null      object
dtypes: float64(1), int64(2), object(4)
memory usage: 464.0+ bytes
None

2.Select only the columns relevant for billing: ['PatientID', 'Department', 'Doctor', 'BillAmount']

In [41]:
patients_filtered = patients[['PatientID', 'Department', 'Doctor', 'BillAmount']]
patients_filtered

   PatientID   Department     Doctor  BillAmount
0        101   Cardiology  Dr. Smith      5000.0
1        102    Neurology   Dr. John         NaN
2        103  Orthopedics    Dr. Lee      7500.0
3        104   Cardiology  Dr. Smith      6200.0
4        105  Dermatology   Dr. Rose         NaN
5        101   Cardiology  Dr. Smith      5000.0

3.Drop administrative columns like ['ReceptionistID', 'CheckInTime']

In [79]:
patients_cleaned=df1.drop(['ReceptionistID', 'CheckInTime'],axis=1)
patients_cleaned

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN
5        101    Alice   Cardiology  Dr. Smith      5000.0

4.Use group  by to find total bill amount per department.

In [80]:
dept_total_bill = patients_cleaned.groupby('Department')['BillAmount'].sum()
print("\nTotal Bill Amount per Department:")
print(dept_total_bill)

Total Bill Amount per Department:
Department
Cardiology     16200.0
Dermatology        0.0
Neurology          0.0
Orthopedics     7500.0
Name: BillAmount, dtype: float64

5.Remove duplicate patient records based on PatientID.

In [81]:
patients_unique = patients_cleaned.drop_duplicates(subset='PatientID', keep='first')
patients_unique

   PatientID     Name   Department     Doctor  BillAmount
0        101    Alice   Cardiology  Dr. Smith      5000.0
1        102      Bob    Neurology   Dr. John         NaN
2        103  Charlie  Orthopedics    Dr. Lee      7500.0
3        104    David   Cardiology  Dr. Smith      6200.0
4        105      Eva  Dermatology   Dr. Rose         NaN

6.Fill missing Bill Amount values with the mean bill amount.

In [85]:
mean_bill = patients_unique['BillAmount'].mean()
patients_unique['BillAmount'] = patients_unique['BillAmount'].fillna(mean_bill)
patients_unique['BillAmount']

0    5000.000000
1    6233.333333
2    7500.000000
3    6200.000000
4    6233.333333
Name: BillAmount, dtype: float64

7.Merge the billing dataset with patient dataset on Patient ID.

In [86]:
merged_df = pd.merge(patients_unique, billing, on='PatientID', how='left')
merged_df

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000

8.Concatenate an additional Data Frame that contains new patients for the current week (row-wise).

In [87]:
Df=pd.DataFrame({
    'PatientID':[201,202],
    'Department':['Cardiology','Dermatology	'],
    'Doctor':['Dr.John','Dr.Joy'],
    'BillAmount':[4500,6000]
})

In [88]:
Df

   PatientID     Department   Doctor  BillAmount
0        201     Cardiology  Dr.John        4500
1        202  Dermatology\t   Dr.Joy        6000

In [89]:
Final_df=pd.concat([merged_df,Df],ignore_index=True)

In [90]:
Final_df

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000.0,3000.0
1,102,Bob,Neurology,Dr. John,6233.333333,1500.0,3500.0
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500.0,5000.0
3,104,David,Cardiology,Dr. Smith,6200.000000,3000.0,3200.0
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000.0,4000.0
5,201,NaN,Cardiology,Dr.John,4500.000000,NaN,NaN
6,202,NaN,Dermatology\t,Dr.Joy,6000.000000,NaN,NaN

9.Concatenate new billing category columns like ['Insurance Covered', 'Final Amount'] (column-wise).

In [95]:
new_columns = pd.DataFrame({
    'Insurance Covered': ['Yes' if x > 3000 else 'No' for x in merged_df ['BillAmount']],
    'Final Amount': merged_df ['BillAmount'] * 0.9   # 10% discount example
})

final_df = pd.concat([merged_df.reset_index(drop=True), new_columns], axis=1)
final_df

,PatientID,Name,Department,Doctor,BillAmount,InsuranceCovered,FinalAmount,Insurance Covered,Final Amount
0,101,Alice,Cardiology,Dr. Smith,5000.000000,2000,3000,Yes,4500.0
1,102,Bob,Neurology,Dr. John,6233.333333,1500,3500,Yes,5610.0
2,103,Charlie,Orthopedics,Dr. Lee,7500.000000,2500,5000,Yes,6750.0
3,104,David,Cardiology,Dr. Smith,6200.000000,3000,3200,Yes,5580.0
4,105,Eva,Dermatology,Dr. Rose,6233.333333,1000,4000,Yes,5610.0

In [96]:
print("\nFinal Cleaned Dataset:")
print(final_df.head())

Final Cleaned Dataset:
   PatientID     Name   Department     Doctor   BillAmount  InsuranceCovered  \
0        101    Alice   Cardiology  Dr. Smith  5000.000000              2000
1        102      Bob    Neurology   Dr. John  6233.333333              1500
2        103  Charlie  Orthopedics    Dr. Lee  7500.000000              2500
3        104    David   Cardiology  Dr. Smith  6200.000000              3000
4        105      Eva  Dermatology   Dr. Rose  6233.333333              1000

   FinalAmount Insurance Covered  Final Amount
0         3000               Yes        4500.0
1         3500               Yes        5610.0
2         5000               Yes        6750.0
3         3200               Yes        5580.0
4         4000               Yes        5610.0