### Section A: Data Structures & Control Structures

##### 1.Create a list of 5 integers. Perform and print the result of the following operations: append, extend, insert, remove, pop, clear, index, count, sort, and reverse.

In [44]:
list=[10,20,50,30,60]
list

[10, 20, 50, 30, 60]

In [45]:
#append
list.append(100)

In [46]:
list.append('python')

In [47]:
list

[10, 20, 50, 30, 60, 100, 'python']

In [48]:
#remove
list.remove('python')
list

[10, 20, 50, 30, 60, 100]

In [49]:
#insert
list.insert(4,200)
list

[10, 20, 50, 30, 200, 60, 100]

In [50]:
list.index(200,4)

4

In [51]:
#Pop
list.pop(4)

200

In [63]:
# count
list.count(60)

1

In [64]:
# sort
list.sort()

In [65]:
list

[10, 20, 30, 50, 60, 100]

In [68]:
#reverse
list.sort(reverse=True)
list

[100, 60, 50, 30, 20, 10]

In [70]:
#extend
list1=[5,4,6]
list2=[8,9,10]
list1.extend(list2)
list1

[5, 4, 6, 8, 9, 10]

In [71]:
list1.clear()

In [72]:
list1

[]

##### 2.Create a tuple that stores 3 student names. Try changing the second name in the tuple. What happens? Explain why.

In [89]:
students=("Rani","Amit","Shashank")

In [95]:
students

('Rani', 'Amit', 'Shashank')

In [96]:
students[1] = "Rahul"

TypeError: 'tuple' object does not support item assignment

######  
 What happens?
TypeError: 'tuple' object does not support item assignment.
Tuples in python are immutable.
Immutable means:once a tuple is created, its values cannot be changed, added, or removed.
That's why when you try to modify students[1], python stops you and  show a type error.
In simple list= change allowed, tuple=change not allowed

###### 3.Create a set of integers with some duplicate values. Print the set and explain the output.

In [108]:
numbers = {1, 2, 3, 2, 4, 3, 5}
print(numbers)

{1, 2, 3, 4, 5}

###### 
A  set in python automatically removes duplicate values.Even though you added repeated numbers(2and 3),the set keeps ony unique elements.That's why the output contains only each number only once.

###### 4.Create a dictionary with the keys: 'name', 'age', and 'city'. Update the age and add a new key 'email'. Print the final dictionary.

In [110]:
dict={"name":"Rani","age":28,"city":"Banglore"}
dict

{'name': 'Rani', 'age': 28, 'city': 'Banglore'}

In [112]:
dict["age"]=22
dict

{'name': 'Rani', 'age': 22, 'city': 'Banglore'}

In [114]:
dict["email"]="ranimali@example.com"
print(dict)

{'name': 'Rani', 'age': 22, 'city': 'Banglore', 'email': 'ranimali@example.com'}

###### 5.Write a script that checks if a person is eligible to vote (age ≥ 18). Take age as a variable and print the appropriate message.

In [126]:
age=18
if age>=18:
    print('eligible to vote')
else:
    print('not eligible to vote')

eligible to vote

###### 6.Given a 'marks' variable, print the grade:
- 90 and above: 'A'
- 75–89: 'B'
- 50–74: 'C'
- Below 50: 'Fail'

In [124]:
##### 
#marks=int(input('Enter the number'))
marks=90
if marks>=90:
  print("Grade is :A" )
elif marks>=75:
  print("Grade is: B")
elif marks>=50:
    print("Grade is: C")
else:
    print("Grade is: Fail")

Grade is :A

###### 7.Given a number, check if it's positive, and if it is also even. If not positive, print if it's zero or negative.

In [132]:
x = int(input("Enter a number: "))

if x > 0:
    if x % 2 == 0:
        print("The number is positive and even.")
    else:
        print("The number is positive but odd.")
elif x == 0:
    print("The number is zero.")
else:
    print("The number is negative.")

Enter a number:  5

The number is positive but odd.

#### Section B: Numpy

###### 8.Create:
- A scalar using np.array(5)
- A 1D array with values 1 to 5
- A 2D array (2x3) with values from 10 to 60 in steps of 10

In [130]:
import numpy as np

In [139]:
scalar = np.array(5)
print("Scalar:\n", scalar)

Scalar:
 5

In [141]:
# 2. Create a 1D array with values 1 to 5
arr_1d = np.array([1, 2, 3, 4, 5])
print("\n1D Array:\n", arr_1d)

1D Array:
 [1 2 3 4 5]

In [142]:
# 3. Create a 2D array (2x3) with values 10 to 60 in steps of 10
arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60]])
print("\n2D Array (2x3):\n", arr_2d)

2D Array (2x3):
 [[10 20 30]
 [40 50 60]]

###### 9.Generate a 4x4 Numpy array of random integers between 0 and 100 using np.random.randint().

In [143]:
two_dim=np.random.randint(1,100,16).reshape(4,4)

In [144]:
two_dim

array([[89, 51, 51, 63],
       [78, 80, 61, 32],
       [67,  5, 22, 17],
       [37, 89, 71, 94]], dtype=int32)

###### 10.Create a 2D numpy array of shape (3x3). Convert it into a pandas DataFrame and add column names: 'A', 'B', 'C'.

In [150]:
import pandas as pd
import numpy as np
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
df=pd.DataFrame(arr,columns=['A','B','C'])
print(df)

   A  B  C
0  1  2  3
1  4  5  6
2  7  8  9

###### Section C: Exploring Pandas

###### 11.Create a small DataFrame manually with 10 rows and columns: 'Name', 'Age', 'City', and 'Salary'. Then:
- Use .info(), .describe()
- Select 'Name' and 'City' columns
- Drop 'City' column
- Fill any missing values in 'Salary' column with the mean
- Remove any duplicate rows

In [153]:

# 1. Create a small DataFrame manually (10 rows)
data = {
    'Name': ['Rani', 'Amit', 'John', 'Sara', 'Amit', 'Kiran', 'Ravi', 'Rani', 'John', 'Meera'],
    'Age': [22, 25, 30, 28, 25, 26, 24, 22, 30, 27],
    'City': ['Mumbai', 'Delhi', 'Pune', 'Mumbai', 'Delhi', 'Chennai', 'Pune', 'Mumbai', 'Pune', 'Delhi'],
    'Salary': [30000, 40000, np.nan, 35000, 40000, 38000, 32000, 30000, np.nan, 45000]
}

df = pd.DataFrame(data)
df

    Name  Age     City   Salary
0   Rani   22   Mumbai  30000.0
1   Amit   25    Delhi  40000.0
2   John   30     Pune      NaN
3   Sara   28   Mumbai  35000.0
4   Amit   25    Delhi  40000.0
5  Kiran   26  Chennai  38000.0
6   Ravi   24     Pune  32000.0
7   Rani   22   Mumbai  30000.0
8   John   30     Pune      NaN
9  Meera   27    Delhi  45000.0

In [154]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10 entries, 0 to 9
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Name    10 non-null     object
 1   Age     10 non-null     int64
 2   City    10 non-null     object
 3   Salary  8 non-null      float64
dtypes: float64(1), int64(1), object(2)
memory usage: 448.0+ bytes

In [155]:
df.describe()

             Age       Salary
count  10.000000      8.00000
mean   25.900000  36250.00000
std     2.884826   5418.22322
min    22.000000  30000.00000
25%    24.250000  31500.00000
50%    25.500000  36500.00000
75%    27.750000  40000.00000
max    30.000000  45000.00000

In [156]:
print(df[['Name', 'City']])

    Name     City
0   Rani   Mumbai
1   Amit    Delhi
2   John     Pune
3   Sara   Mumbai
4   Amit    Delhi
5  Kiran  Chennai
6   Ravi     Pune
7   Rani   Mumbai
8   John     Pune
9  Meera    Delhi

In [157]:
df_dropped = df.drop('City', axis=1)

In [158]:
df_dropped

    Name  Age   Salary
0   Rani   22  30000.0
1   Amit   25  40000.0
2   John   30      NaN
3   Sara   28  35000.0
4   Amit   25  40000.0
5  Kiran   26  38000.0
6   Ravi   24  32000.0
7   Rani   22  30000.0
8   John   30      NaN
9  Meera   27  45000.0